### PR TITLE
Configure a timeout on SenderBase.

### PR DESCRIPTION
**Pull request by mopaul**
Helps with [Issue-16](https://github.com/Microsoft/ApplicationInsights-Python/issues/16)

### CODE REVIEW

**Comment by OsvaldoRosado** [comment]
Can you retarget this against the develop branch? Thanks!

**Comment by mopaul** [comment]
Thanks for looking into this. When will it be pulled into master and patch released?

**Comment by OsvaldoRosado** [comment]
@mopaul We don't currently have an ETA for a new master release

**Comment by turowicz** [comment]
@mopaul @OsvaldoRosado I just started getting #16 issue which this commit is supposed to fix.

**Pull request merged**
