### PR TITLE
Adding cloud_RoleName and cloud_RoleInstance

### PR DESCRIPTION
**Pull request by gugu91**
Added support for shipping Cloud class to Application Insights

### CODE REVIEW

**Comment by gugu91** [comment]
Related to #119

**Comment by gugu91** [comment]
@SergeyKanzhelev can you help with the review? Ideally would like this merged as we are using this client in a production system and had to monkey patch it!

Thanks!

**Comment by SergeyKanzhelev** [comment]
Sorry for delay and thanks for contribution. Can you please update `CHANGELOG.md` and I'll merge it and release a new version

**Comment by gugu91** [comment]
@SergeyKanzhelev I've modified the changelog. Please feel free to edit it.

**Comment by gugu91** [comment]
@SergeyKanzhelev did you have a chance to have a look at it? Can you merge it if it's alright? Thanks!

**Pull request merged**
