### PR TITLE
Added track_dependency

### PR DESCRIPTION
**Pull request by dstockhammer**
I understand that there is work under way to move to OpenCensus, which may then cover this use case.
In the meantime, I've added this method which should be in line with the current design.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Travis failed. Have I merged incorrectly? Can you please update PR?

Yes, directionally we will be moving to Open Census. We may need to keep API layer that simply allows to create and send data types. As Application Insights has more data types than Census.

**Comment by dstockhammer** [comment]
The tests were passing locally, I swear :see_no_evil:

The type hints were the culprit, apologies. Didn't realise that the lib targets 2.7 and 3.4

**Comment by dstockhammer** [comment]
@SergeyKanzhelev do you have a planned release date for these changes? We're currently using a patched `TelemetryClient` in our projects, but being able to just use the vanilla one would make our lives considerably easier.

**Comment by SergeyKanzhelev** [comment]
@dstockhammer published. Let me know if you have any troubles with it

**Pull request merged**
